version: '3.7'

services:
  web:
    build: .
    command: python djangoprj/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 8080:80
    env_file:
      - ./djangoprj/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=unlocode
      - POSTGRES_USER=locode
      - POSTGRES_PASSWORD=locode

volumes:
  postgres_data: