# Generated by Django 3.0.6 on 2020-05-30 22:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unlocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch', models.CharField(max_length=1)),
                ('locode', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('namewodiacritics', models.CharField(max_length=100)),
                ('subdiv', models.CharField(max_length=3)),
                ('functions', multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Unknown'), ('1', 'Port'), ('2', 'Rail'), ('3', 'Road'), ('4', 'Airport'), ('5', 'Post'), ('6', 'Multimod'), ('7', 'FixTrans'), ('B', 'Border')], max_length=17)),
                ('status', models.CharField(max_length=2)),
                ('date', models.CharField(max_length=4)),
                ('iata', models.CharField(max_length=3)),
                ('coordinates', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['locode'],
            },
        ),
    ]
